"""followers

Revision ID: 165a2c787db7
Revises: 10a0e4843e65
Create Date: 2018-09-04 10:28:52.301621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165a2c787db7'
down_revision = '10a0e4843e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
